package kounettechnologie.kounet.multiconnexions.web;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2024-09-11T23:52:11.318-04:00
 * Generated source version: 4.0.0
 *
 */
@WebService(targetNamespace = "http://web.multiconnexions.kounet.kounettechnologie/", name = "CustomerSoapService")
@XmlSeeAlso({ObjectFactory.class})
public interface CustomerSoapService {

    @WebMethod
    @RequestWrapper(localName = "saveCustomer", targetNamespace = "http://web.multiconnexions.kounet.kounettechnologie/", className = "kounettechnologie.kounet.multiconnexions.web.SaveCustomer")
    @ResponseWrapper(localName = "saveCustomerResponse", targetNamespace = "http://web.multiconnexions.kounet.kounettechnologie/", className = "kounettechnologie.kounet.multiconnexions.web.SaveCustomerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public kounettechnologie.kounet.multiconnexions.web.Customer saveCustomer(

        @WebParam(name = "customer", targetNamespace = "")
        kounettechnologie.kounet.multiconnexions.web.CustomerRequest customer
    );

    @WebMethod
    @RequestWrapper(localName = "customerById", targetNamespace = "http://web.multiconnexions.kounet.kounettechnologie/", className = "kounettechnologie.kounet.multiconnexions.web.CustomerById")
    @ResponseWrapper(localName = "customerByIdResponse", targetNamespace = "http://web.multiconnexions.kounet.kounettechnologie/", className = "kounettechnologie.kounet.multiconnexions.web.CustomerByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public kounettechnologie.kounet.multiconnexions.web.Customer customerById(

        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    );

    @WebMethod
    @RequestWrapper(localName = "customerList", targetNamespace = "http://web.multiconnexions.kounet.kounettechnologie/", className = "kounettechnologie.kounet.multiconnexions.web.CustomerList")
    @ResponseWrapper(localName = "customerListResponse", targetNamespace = "http://web.multiconnexions.kounet.kounettechnologie/", className = "kounettechnologie.kounet.multiconnexions.web.CustomerListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<kounettechnologie.kounet.multiconnexions.web.Customer> customerList()
;
}
